/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ImuConnectionJ */

#ifndef _Included_ImuConnectionJ
#define _Included_ImuConnectionJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ImuConnectionJ
 * Method:    startImu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ImuConnectionJ_startImu
  (JNIEnv *, jobject);

/*
 * Class:     ImuConnectionJ
 * Method:    getPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ImuConnectionJ_getPosition
  (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
